import numpy as np

nodes = {
    1:{
        "Node ID": 1,
        "Position": (10, 100),
        "Neighbors": [2,3,4,5],
        "Initial Energy": 100,
        "Residual Energy": 95,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    2:{
        "Node ID": 2,
        "Position": (50,50),
        "Neighbors": [6,7,8,9,10],
        "Initial Energy": 98,
        "Residual Energy": 90,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    3:{
        "Node ID": 3,
        "Position": (50,100),
        "Neighbors": [6,7,8,9,10],
        "Initial Energy": 95,
        "Residual Energy": 95,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    4:{
        "Node ID": 4,
        "Position": (50,150),
        "Neighbors": [6,7,8,9,10],
        "Initial Energy": 90,
        "Residual Energy": 75,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    5:{
        "Node ID": 5,
        "Position": (50,200),
        "Neighbors": [6,7,8,9,10],
        "Initial Energy": 85,
        "Residual Energy": 25,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    6:{
        "Node ID": 6,
        "Position": (100,40),
        "Neighbors": [11,12,13,14,15],
        "Initial Energy": 83,
        "Residual Energy": 50,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    7:{
        "Node ID": 7,
        "Position": (100,80),
        "Neighbors": [11,12,13,14,15],
        "Initial Energy": 87,
        "Residual Energy": 77,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    8:{
        "Node ID": 8,
        "Position": (100,120),
        "Neighbors": [11,12,13,14,15],
        "Initial Energy": 73,
        "Residual Energy": 70,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    9:{
        "Node ID": 9,
        "Position": (100,160),
        "Neighbors": [11,12,13,14,15],
        "Initial Energy": 65,
        "Residual Energy": 62,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    10:{
        "Node ID": 10,
        "Position": (100,200),
        "Neighbors": [11,12,13,14,15],
        "Initial Energy": 60,
        "Residual Energy": 30,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    11:{
        "Node ID": 11,
        "Position": (150,40),
        "Neighbors": [16,17,18,19,20],
        "Initial Energy": 55,
        "Residual Energy": 55,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    12:{
        "Node ID": 12,
        "Position": (150,80),
        "Neighbors": [16,17,18,19,20],
        "Initial Energy": 30,
        "Residual Energy": 25,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    13:{
        "Node ID": 13,
        "Position": (150,120),
        "Neighbors": [16,17,18,19,20],
        "Initial Energy": 45,
        "Residual Energy": 45,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    14:{
        "Node ID": 14,
        "Position": (150,160),
        "Neighbors": [16,17,18,19,20],
        "Initial Energy": 38,
        "Residual Energy": 38,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    15:{
        "Node ID": 15,
        "Position": (150,200),
        "Neighbors": [16,17,18,19,20],
        "Initial Energy": 35,
        "Residual Energy": 22,
        "PRR": np.random.uniform(0.8, 0.91),
        "Buffer Capacity": np.random.randint(8, 11),
        "Free Buffer": np.random.randint(8, 11),
        "Data Packet": {},
        "PTR": 0.88,
    },
    16:{
        "Node ID": 16,
        "Position": (200, 40),
        "Neighbors": [21,22,23,24],
        "Initial Energy": 95,
        "Residual Energy": 90,
        "PRR": 0.85,
        "Buffer Capacity": 10,
        "Free Buffer": 8,
        "Data Packet": {},
        "PTR": 0.88
    },
    17:{
        "Node ID": 17,
        "Position": (200, 80),
        "Neighbors": [21,22,23,24],
        "Initial Energy": 93,
        "Residual Energy": 85,
        "PRR": 0.87,
        "Buffer Capacity": 9,
        "Free Buffer": 9,
        "Data Packet": {},
        "PTR": 0.88
    },
    18:{
        "Node ID": 18,
        "Position": (200, 120),
        "Neighbors": [21,22,23,24],
        "Initial Energy": 88,
        "Residual Energy": 78,
        "PRR": 0.86,
        "Buffer Capacity": 8,
        "Free Buffer": 7,
        "Data Packet": {},
        "PTR": 0.88
    },
    19:{
        "Node ID": 19,
        "Position": (200, 160),
        "Neighbors": [21,22,23,24],
        "Initial Energy": 85,
        "Residual Energy": 75,
        "PRR": 0.89,
        "Buffer Capacity": 9,
        "Free Buffer": 8,
        "Data Packet": {},
        "PTR": 0.88
    },
    20:{
        "Node ID": 20,
        "Position": (200, 200),
        "Neighbors": [21,22,23,24],
        "Initial Energy": 92,
        "Residual Energy": 88,
        "PRR": 0.88,
        "Buffer Capacity": 8,
        "Free Buffer": 8,
        "Data Packet": {},
        "PTR": 0.88
    },
    21:{
        "Node ID": 21,
        "Position": (250, 50),
        "Neighbors": [25],
        "Initial Energy": 91,
        "Residual Energy": 83,
        "PRR": 0.9,
        "Buffer Capacity": 9,
        "Free Buffer": 9,
        "Data Packet": {},
        "PTR": 0.88
    },
    22:{
        "Node ID": 22,
        "Position": (250, 100),
        "Neighbors": [25],
        "Initial Energy": 87,
        "Residual Energy": 79,
        "PRR": 0.86,
        "Buffer Capacity": 8,
        "Free Buffer": 7,
        "Data Packet": {},
        "PTR": 0.88
    },
    23:{
        "Node ID": 23,
        "Position": (250, 150),
        "Neighbors": [25],
        "Initial Energy": 83,
        "Residual Energy": 77,
        "PRR": 0.89,
        "Buffer Capacity": 9,
        "Free Buffer": 8,
        "Data Packet": {},
        "PTR": 0.88
    },
    24:{
        "Node ID": 24,
        "Position": (250, 200),
        "Neighbors": [25],
        "Initial Energy": 89,
        "Residual Energy": 82,
        "PRR": 0.87,
        "Buffer Capacity": 8,
        "Free Buffer": 7,
        "Data Packet": {},
        "PTR": 0.88
    },
    25:{
        "Node ID": 25,
        "Position": (290, 125),
        "Neighbors": [],
        "Initial Energy": 90,
        "Residual Energy": 85,
        "PRR": 0.9,
        "Buffer Capacity": 10,
        "Free Buffer": 9,
        "Data Packet": {},
        "PTR": 0.88
    }
}
